package com.he194346.mvc.online_library_management_system.enums;

public enum ErrorCode {
    USER_ALREADY_EXISTS,
    CATEGORY_NOT_FOUND,
    CATEGORY_ALREADY_EXISTS,
    AUTHOR_NOT_FOUND,
    AUTHOR_ALREADY_EXISTS,
    BOOK_NOT_FOUND,
    BOOK_ALREADY_EXISTS,
    RESERVATION_NOT_FOUND,
    INVALID_RESERVATION,
    INSUFFICIENT_BOOK_COPIES,
}
